import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "@mantine/core/styles.css";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { LocalePageProps } from "./ts/locale";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../mantine/theme";
import Header from "./components/nav/header";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reddit Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: LocalePageProps;
}>) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Header />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
